version: '2'
services:
    preonboardin-app:
        image: preonboardin
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://preonboardin-postgresql:5432/Preonboardin
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    preonboardin-postgresql:
        extends:
            file: postgresql.yml
            service: preonboardin-postgresql
